parameters:
#    projet_k_pret.example.class: ProjetK\PretBundle\Example

services:
#    projet_k_pret.example:
#        class: %projet_k_pret.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
