parameters:
#    projet_k_pret.example.class: ProjetK\PretBundle\Example

services:
  form.type.datePicker:
    class: ProjetK\PretBundle\Form\Type\DatePickerType
    tags:
      - { name: form.type, alias: datePicker }
